# Generated by Django 3.2.12 on 2023-01-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'managed': False},
        ),
    ]
