# Generated by Django 3.2.12 on 2023-01-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_website', '0002_alter_pizza_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pizza',
            table='Pizza.Pizza',
        ),
    ]
