# Generated by Django 3.2.12 on 2023-01-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_website', '0003_alter_pizza_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pizza',
            table='PIZZA.Pizza',
        ),
    ]
